/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTop3RouteImport } from './routes/_authenticated/top3'
import { Route as AuthenticatedTopScorersRouteImport } from './routes/_authenticated/top-scorers'
import { Route as AuthenticatedSquadsRouteImport } from './routes/_authenticated/squads'
import { Route as AuthenticatedMyPredictionsRouteImport } from './routes/_authenticated/my-predictions'
import { Route as AuthenticatedMatchesRouteImport } from './routes/_authenticated/matches'
import { Route as AuthenticatedLeaderboardRouteImport } from './routes/_authenticated/leaderboard'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedBracketRouteImport } from './routes/_authenticated/bracket'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ApiPublicDiagRouteImport } from './routes/api/public/diag'

const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTop3Route = AuthenticatedTop3RouteImport.update({
  id: '/top3',
  path: '/top3',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTopScorersRoute = AuthenticatedTopScorersRouteImport.update({
  id: '/top-scorers',
  path: '/top-scorers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSquadsRoute = AuthenticatedSquadsRouteImport.update({
  id: '/squads',
  path: '/squads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyPredictionsRoute =
  AuthenticatedMyPredictionsRouteImport.update({
    id: '/my-predictions',
    path: '/my-predictions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMatchesRoute = AuthenticatedMatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeaderboardRoute =
  AuthenticatedLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBracketRoute = AuthenticatedBracketRouteImport.update({
  id: '/bracket',
  path: '/bracket',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicDiagRoute = ApiPublicDiagRouteImport.update({
  id: '/api/public/diag',
  path: '/api/public/diag',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rules': typeof RulesRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/bracket': typeof AuthenticatedBracketRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/matches': typeof AuthenticatedMatchesRoute
  '/my-predictions': typeof AuthenticatedMyPredictionsRoute
  '/squads': typeof AuthenticatedSquadsRoute
  '/top-scorers': typeof AuthenticatedTopScorersRoute
  '/top3': typeof AuthenticatedTop3Route
  '/api/public/diag': typeof ApiPublicDiagRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rules': typeof RulesRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/bracket': typeof AuthenticatedBracketRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/matches': typeof AuthenticatedMatchesRoute
  '/my-predictions': typeof AuthenticatedMyPredictionsRoute
  '/squads': typeof AuthenticatedSquadsRoute
  '/top-scorers': typeof AuthenticatedTopScorersRoute
  '/top3': typeof AuthenticatedTop3Route
  '/api/public/diag': typeof ApiPublicDiagRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rules': typeof RulesRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/bracket': typeof AuthenticatedBracketRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/_authenticated/matches': typeof AuthenticatedMatchesRoute
  '/_authenticated/my-predictions': typeof AuthenticatedMyPredictionsRoute
  '/_authenticated/squads': typeof AuthenticatedSquadsRoute
  '/_authenticated/top-scorers': typeof AuthenticatedTopScorersRoute
  '/_authenticated/top3': typeof AuthenticatedTop3Route
  '/api/public/diag': typeof ApiPublicDiagRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/rules'
    | '/admin'
    | '/bracket'
    | '/dashboard'
    | '/leaderboard'
    | '/matches'
    | '/my-predictions'
    | '/squads'
    | '/top-scorers'
    | '/top3'
    | '/api/public/diag'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/rules'
    | '/admin'
    | '/bracket'
    | '/dashboard'
    | '/leaderboard'
    | '/matches'
    | '/my-predictions'
    | '/squads'
    | '/top-scorers'
    | '/top3'
    | '/api/public/diag'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/rules'
    | '/_authenticated/admin'
    | '/_authenticated/bracket'
    | '/_authenticated/dashboard'
    | '/_authenticated/leaderboard'
    | '/_authenticated/matches'
    | '/_authenticated/my-predictions'
    | '/_authenticated/squads'
    | '/_authenticated/top-scorers'
    | '/_authenticated/top3'
    | '/api/public/diag'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RulesRoute: typeof RulesRoute
  ApiPublicDiagRoute: typeof ApiPublicDiagRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/top3': {
      id: '/_authenticated/top3'
      path: '/top3'
      fullPath: '/top3'
      preLoaderRoute: typeof AuthenticatedTop3RouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/top-scorers': {
      id: '/_authenticated/top-scorers'
      path: '/top-scorers'
      fullPath: '/top-scorers'
      preLoaderRoute: typeof AuthenticatedTopScorersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/squads': {
      id: '/_authenticated/squads'
      path: '/squads'
      fullPath: '/squads'
      preLoaderRoute: typeof AuthenticatedSquadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-predictions': {
      id: '/_authenticated/my-predictions'
      path: '/my-predictions'
      fullPath: '/my-predictions'
      preLoaderRoute: typeof AuthenticatedMyPredictionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/matches': {
      id: '/_authenticated/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof AuthenticatedMatchesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leaderboard': {
      id: '/_authenticated/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AuthenticatedLeaderboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bracket': {
      id: '/_authenticated/bracket'
      path: '/bracket'
      fullPath: '/bracket'
      preLoaderRoute: typeof AuthenticatedBracketRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/diag': {
      id: '/api/public/diag'
      path: '/api/public/diag'
      fullPath: '/api/public/diag'
      preLoaderRoute: typeof ApiPublicDiagRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedBracketRoute: typeof AuthenticatedBracketRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLeaderboardRoute: typeof AuthenticatedLeaderboardRoute
  AuthenticatedMatchesRoute: typeof AuthenticatedMatchesRoute
  AuthenticatedMyPredictionsRoute: typeof AuthenticatedMyPredictionsRoute
  AuthenticatedSquadsRoute: typeof AuthenticatedSquadsRoute
  AuthenticatedTopScorersRoute: typeof AuthenticatedTopScorersRoute
  AuthenticatedTop3Route: typeof AuthenticatedTop3Route
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedBracketRoute: AuthenticatedBracketRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLeaderboardRoute: AuthenticatedLeaderboardRoute,
  AuthenticatedMatchesRoute: AuthenticatedMatchesRoute,
  AuthenticatedMyPredictionsRoute: AuthenticatedMyPredictionsRoute,
  AuthenticatedSquadsRoute: AuthenticatedSquadsRoute,
  AuthenticatedTopScorersRoute: AuthenticatedTopScorersRoute,
  AuthenticatedTop3Route: AuthenticatedTop3Route,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RulesRoute: RulesRoute,
  ApiPublicDiagRoute: ApiPublicDiagRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
